---
version: "3.7"

services:

  postgres:
    container_name: postgres
    image: postgres:14-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_HOST_AUTH_METHOD: 'trust'

volumes:
  postgres_data:

networks:
  dbt_network:
    driver: bridge